"use client"
import React, { useState, useEffect } from 'react';
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";
import Navbar from "@/components/custom/Navbar";
import Footer from "@/components/custom/Footer";
import Preloader from "@/components/custom/Preloader";
import CustomCursor from '@/components/custom/CustomCursor';

const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate a loading delay
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2000); // Adjust the delay as needed

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <body className={`${montserrat.className} mx-auto bg-black`}>
        {loading ? (
          <Preloader />
        ) : (
          <>
            <Navbar />
            {children}
            <Footer />
            <CustomCursor />  
          </>
        )}
      </body>
    </html>
  );
}